global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    scrape_interval: 10s 
    static_configs: 
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis_exporter'
    static_configs:
    - targets: ['redis_exporter:9121']

  - job_name: 'sidekiq_exporter'
    static_configs:
    - targets: ['sidekiq_exporter:9292']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

